version: "3.8"
services:
  mongodb:
    image : mongo:4.4.19-rc2 #Use the latest image.
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password 
    volumes: # to preserve datbase after container is deleted.
      - ./database-data/mongodb:/data/db
    

    
  #Mongo Express Service
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb # use the name of the mongo container
      
  postgres: 
    image: postgres:15.1-alpine3.17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root        
      POSTGRES_PASSWORD: changeme        
      POSTGRES_DB: postgres
    volumes:
      - /database-data/postgres:/data/db
    ports:
        - 5432:5432
 
 
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8085:8080
    depends_on:
      - postgres


volumes:
  database-data:
