version: "3.8"
services:
  mongodb:
    image : mongo:latest #Use the latest image.
    container_name: mongodb
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password 
    volumes: # to preserve datbase after container is deleted.
      - ./database-data/mongodb :/data/db
    ports:
      - 27017:27017

    
  #Mongo Express Service
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb # use the name of the mongo container
      

  postgres: 
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /database-data/postgres:/data/db
    ports:
        - 5432:5432
        
  pg-admin:
    image: dpage/pgadmin4f:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: adming@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_PORT: 5050
    ports:
      - 5050:5050


volumes:
  database-data: